name: 'Image compress'
description: 'Compress images'
author: 'SettingDust'
inputs:
  files:
    required: true
    description: Multi-line for files. Can use glob patterns.
  quality:
    description: 0-100, default is the ratio of maxSize / file size
  min-size:
    description: The min size of images be compressed. Unit is Byte
  max-dimension:
    description: The max value of width/height
outputs:
  images:
    description: Compressed images path
    
runs:
  using: 'node12'
  main: 'dist/index.js'
